services:
  postgres:
    image: postgres:17.0-bookworm
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: vde_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "8082:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  springboot-app:
    build: .
    container_name: Backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      # Configuration de la base PostgreSQL
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/vde_database
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
      SPRING_JPA_OPEN-IN-VIEW: false

      #  Configuration de Hibernate (ORM)
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"

      #  Configuration des logs pour voir les requêtes SQL
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: DEBUG
      LOGGING_LEVEL_ORG_HIBERNATE_SQL: DEBUG
      LOGGING_LEVEL_ORG_HIBERNATE_TYPE_DESCRIPTOR_SQL_BASICBINDER: TRACE

      #  Configuration JWT
      JWT_SECRET: coolkey-secret-key  # Clé secrète pour les tokens JWT

      #  Autres configurations
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "*"
      SPRING_MAIN_ALLOW_CIRCULAR_REFERENCES: "true"

    volumes:
      - ./logs:/logs  #  Synchronisation des logs


volumes:
  postgres_data:
  pgadmin_data: